### ISSUE TITLE
Nusense

### ISSUE THREAD

**Issue by fqy2333** [Nightmare-n/PVT-SSD#7]
作者你好 工作非常好 请问一下有NuScenes数据集的配置文件吗

**Comment by Nightmare-n** [comment]
```
    POST_PROCESSING:
        RECALL_THRESH_LIST: [0.3, 0.5, 0.7]
        SCORE_THRESH: 0.1
        OUTPUT_RAW_SCORE: False

        EVAL_METRIC: kitti

        NMS_CONFIG:
            MULTI_CLASSES_NMS: False
            NMS_TYPE: nms_gpu
            NMS_THRESH: 0.2
            NMS_PRE_MAXSIZE: 4096
            NMS_POST_MAXSIZE: 500


OPTIMIZATION:
    BATCH_SIZE_PER_GPU: 16
    NUM_EPOCHS: 4

    OPTIMIZER: adam_onecycle
    LR: 0.002
    WEIGHT_DECAY: 0.01
    MOMENTUM: 0.9

    MOMS: [0.95, 0.85]
    PCT_START: 0.4
    DIV_FACTOR: 10
    DECAY_STEP_LIST: [35, 45]
    LR_DECAY: 0.1
    LR_CLIP: 0.0000001

    LR_WARMUP: False
    WARMUP_EPOCH: 1

    GRAD_NORM_CLIP: 10

```

学习率配置如上，网络配置和waymo的cfg一样。在nuscenes上没用rv-based query，而是直接用的ball query，需要修改下代码。
